import '../../presentation/widgets/icons/app_icon_type.dart';
import '../../domain/conditions/achievement_condition.dart';
import '../../domain/entities/achievement.dart';
import '../../domain/enums/achievement_rarity.dart';
import '../../domain/enums/activity_tag.dart';

final List<Achievement> kAllAchievements = [
  // ========== COMMON (★) ==========

  const Achievement(
    id: 'first_log',
    title: '暇人への第一歩',
    description: '初めてログを記録する',
    icon: AppIconType.footprint,
    rarity: AchievementRarity.common,
    condition: FirstLogCondition(),
  ),
  const Achievement(
    id: 'first_nap',
    title: '昼寝デビュー',
    description: '昼寝を初めてログする',
    icon: AppIconType.nap,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.nap),
  ),
  const Achievement(
    id: 'first_walk',
    title: '散歩デビュー',
    description: '散歩を初めてログする',
    icon: AppIconType.walk,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.walk),
  ),
  const Achievement(
    id: 'first_nothing',
    title: '何もしない勇気',
    description: '「何もしない」を初めてログする',
    icon: AppIconType.cloud,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.nothing),
  ),
  const Achievement(
    id: 'first_tv',
    title: '動画解禁',
    description: '動画/TVを初めてログする',
    icon: AppIconType.tv,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.tv),
  ),
  const Achievement(
    id: 'first_read',
    title: '読書開始',
    description: '読書を初めてログする',
    icon: AppIconType.books,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.read),
  ),
  const Achievement(
    id: 'first_bath',
    title: '湯船の誘惑',
    description: 'お風呂を初めてログする',
    icon: AppIconType.bathtub,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.bath),
  ),
  const Achievement(
    id: 'first_music',
    title: '耳を解放する',
    description: '音楽を初めてログする',
    icon: AppIconType.musicNote,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.music),
  ),
  const Achievement(
    id: 'first_game',
    title: 'ゲームスタート',
    description: 'ゲームを初めてログする',
    icon: AppIconType.gameController,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.game),
  ),
  const Achievement(
    id: 'first_cafe',
    title: 'カフェ常連への道',
    description: 'カフェを初めてログする',
    icon: AppIconType.coffee,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.cafe),
  ),
  const Achievement(
    id: 'first_food',
    title: '食を記録する',
    description: '食事/料理を初めてログする',
    icon: AppIconType.cooking,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.food),
  ),
  const Achievement(
    id: 'first_exercise',
    title: '体を動かしてみた',
    description: '運動を初めてログする',
    icon: AppIconType.muscle,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.exercise),
  ),
  const Achievement(
    id: 'first_creative',
    title: '創作の芽',
    description: '創作を初めてログする',
    icon: AppIconType.pencil,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.creative),
  ),
  const Achievement(
    id: 'first_social',
    title: '話してみた',
    description: 'おしゃべりを初めてログする',
    icon: AppIconType.chatBubble,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.social),
  ),
  const Achievement(
    id: 'first_shopping',
    title: 'ウィンドウショッピング',
    description: '買い物を初めてログする',
    icon: AppIconType.shoppingBags,
    rarity: AchievementRarity.common,
    condition: FirstTagCondition(ActivityTag.shopping),
  ),
  const Achievement(
    id: 'night_owl',
    title: '夜型暇人',
    description: '深夜0時以降にログを記録する',
    icon: AppIconType.owl,
    rarity: AchievementRarity.common,
    condition: TimeOfDayCondition(startHour: 0, endHour: 4),
  ),
  const Achievement(
    id: 'early_bird',
    title: '早起き暇人',
    description: '朝6時前にログを記録する',
    icon: AppIconType.sunrise,
    rarity: AchievementRarity.common,
    condition: TimeOfDayCondition(startHour: 4, endHour: 6),
  ),
  const Achievement(
    id: 'three_days',
    title: '3日坊主じゃない',
    description: '3日連続でログを記録する',
    icon: AppIconType.calendar,
    rarity: AchievementRarity.common,
    condition: ConsecutiveDaysCondition(3),
  ),
  const Achievement(
    id: 'log_5',
    title: '記録魔への道',
    description: '合計5件のログを記録する',
    icon: AppIconType.checkMark,
    rarity: AchievementRarity.common,
    condition: TotalCountCondition(5),
  ),
  const Achievement(
    id: 'nap_3',
    title: '昼寝の習慣',
    description: '昼寝を3回ログする',
    icon: AppIconType.sleepZzz,
    rarity: AchievementRarity.common,
    condition: TagCountCondition(ActivityTag.nap, 3),
  ),
  const Achievement(
    id: 'nothing_60min',
    title: '何もしない達人',
    description: '「何もしない」を1時間ログする',
    icon: AppIconType.fog,
    rarity: AchievementRarity.common,
    condition: SingleSessionDurationCondition(ActivityTag.nothing, 60),
  ),
  const Achievement(
    id: 'walk_3',
    title: '散歩好き',
    description: '散歩を3回ログする',
    icon: AppIconType.shoe,
    rarity: AchievementRarity.common,
    condition: TagCountCondition(ActivityTag.walk, 3),
  ),
  const Achievement(
    id: 'tv_3',
    title: '動画三昧',
    description: '動画/TVを3回ログする',
    icon: AppIconType.popcorn,
    rarity: AchievementRarity.common,
    condition: TagCountCondition(ActivityTag.tv, 3),
  ),
  const Achievement(
    id: 'afternoon_logger',
    title: '午後の暇人',
    description: '午後2〜5時にログを記録する',
    icon: AppIconType.partlyCloudy,
    rarity: AchievementRarity.common,
    condition: TimeOfDayCondition(startHour: 14, endHour: 17),
  ),
  const Achievement(
    id: 'bath_30min',
    title: '入浴好き',
    description: 'お風呂を30分以上ログする',
    icon: AppIconType.bubbles,
    rarity: AchievementRarity.common,
    condition: SingleSessionDurationCondition(ActivityTag.bath, 30),
  ),

  // ========== UNCOMMON (★★) ==========

  const Achievement(
    id: 'nap_10',
    title: '昼寝マスター',
    description: '昼寝を10回ログする',
    icon: AppIconType.bed,
    rarity: AchievementRarity.uncommon,
    condition: TagCountCondition(ActivityTag.nap, 10),
  ),
  const Achievement(
    id: 'week_streak',
    title: '7日連続暇人',
    description: '7日連続でログを記録する',
    icon: AppIconType.calendarSpiral,
    rarity: AchievementRarity.uncommon,
    condition: ConsecutiveDaysCondition(7),
  ),
  const Achievement(
    id: 'bath_60min',
    title: '風呂哲学者',
    description: 'お風呂を1時間以上ログする',
    icon: AppIconType.brain,
    rarity: AchievementRarity.uncommon,
    condition: SingleSessionDurationCondition(ActivityTag.bath, 60),
  ),
  const Achievement(
    id: 'nothing_2h',
    title: '虚無の境地',
    description: '「何もしない」を2時間ログする',
    icon: AppIconType.hole,
    rarity: AchievementRarity.uncommon,
    condition: SingleSessionDurationCondition(ActivityTag.nothing, 120),
  ),
  const Achievement(
    id: 'midnight_logger',
    title: '深夜の独り言',
    description: '深夜2時以降にログを記録する',
    icon: AppIconType.moon,
    rarity: AchievementRarity.uncommon,
    condition: TimeOfDayCondition(startHour: 2, endHour: 4),
  ),
  const Achievement(
    id: 'walk_10',
    title: '散歩常連',
    description: '散歩を10回ログする',
    icon: AppIconType.map,
    rarity: AchievementRarity.uncommon,
    condition: TagCountCondition(ActivityTag.walk, 10),
  ),
  const Achievement(
    id: 'tv_4h',
    title: '動画一気見',
    description: '動画/TVを4時間以上ログする',
    icon: AppIconType.clapperboard,
    rarity: AchievementRarity.uncommon,
    condition: SingleSessionDurationCondition(ActivityTag.tv, 240),
  ),
  const Achievement(
    id: 'read_10',
    title: '読書家',
    description: '読書を10回ログする',
    icon: AppIconType.bookmark,
    rarity: AchievementRarity.uncommon,
    condition: TagCountCondition(ActivityTag.read, 10),
  ),
  const Achievement(
    id: 'game_5h',
    title: 'ゲーマー',
    description: 'ゲームを合計5時間ログする',
    icon: AppIconType.joystick,
    rarity: AchievementRarity.uncommon,
    condition: TagDurationCondition(ActivityTag.game, 300),
  ),
  const Achievement(
    id: 'cafe_5',
    title: 'カフェ常連',
    description: 'カフェを5回ログする',
    icon: AppIconType.store,
    rarity: AchievementRarity.uncommon,
    condition: TagCountCondition(ActivityTag.cafe, 5),
  ),
  const Achievement(
    id: 'log_30',
    title: '記録の鬼',
    description: '合計30件のログを記録する',
    icon: AppIconType.clipboard,
    rarity: AchievementRarity.uncommon,
    condition: TotalCountCondition(30),
  ),
  const Achievement(
    id: 'walk_2h',
    title: '長距離散歩者',
    description: '散歩を2時間以上ログする',
    icon: AppIconType.hikingBoot,
    rarity: AchievementRarity.uncommon,
    condition: SingleSessionDurationCondition(ActivityTag.walk, 120),
  ),
  const Achievement(
    id: 'nothing_total_5h',
    title: '怠惰の哲学者',
    description: '「何もしない」を合計5時間ログする',
    icon: AppIconType.meditation,
    rarity: AchievementRarity.uncommon,
    condition: TagDurationCondition(ActivityTag.nothing, 300),
  ),
  const Achievement(
    id: 'music_total_10h',
    title: '音楽狂',
    description: '音楽を合計10時間ログする',
    icon: AppIconType.headphones,
    rarity: AchievementRarity.uncommon,
    condition: TagDurationCondition(ActivityTag.music, 600),
  ),
  const Achievement(
    id: 'creative_5',
    title: 'クリエイター見習い',
    description: '創作を5回ログする',
    icon: AppIconType.palette,
    rarity: AchievementRarity.uncommon,
    condition: TagCountCondition(ActivityTag.creative, 5),
  ),
  const Achievement(
    id: 'social_5',
    title: '社交の暇人',
    description: 'おしゃべりを5回ログする',
    icon: AppIconType.speakingHead,
    rarity: AchievementRarity.uncommon,
    condition: TagCountCondition(ActivityTag.social, 5),
  ),
  const Achievement(
    id: 'exercise_5',
    title: 'ゆるっと運動家',
    description: '運動を5回ログする',
    icon: AppIconType.running,
    rarity: AchievementRarity.uncommon,
    condition: TagCountCondition(ActivityTag.exercise, 5),
  ),
  const Achievement(
    id: '5_tags_used',
    title: '多彩な暇つぶし',
    description: '5種類以上のタグを使う',
    icon: AppIconType.rainbow,
    rarity: AchievementRarity.uncommon,
    condition: MinTagVarietyCondition(5),
  ),
  const Achievement(
    id: 'morning_logger',
    title: '朝の記録家',
    description: '朝7〜9時にログを記録する',
    icon: AppIconType.sun,
    rarity: AchievementRarity.uncommon,
    condition: TimeOfDayCondition(startHour: 7, endHour: 9),
  ),
  const Achievement(
    id: 'nap_total_10h',
    title: '眠り姫',
    description: '昼寝を合計10時間ログする',
    icon: AppIconType.princess,
    rarity: AchievementRarity.uncommon,
    condition: TagDurationCondition(ActivityTag.nap, 600),
  ),

  // ========== RARE (★★★) ==========

  const Achievement(
    id: 'nap_3_in_day',
    title: '今日も3回昼寝した',
    description: '1日に昼寝を3回ログする',
    icon: AppIconType.sleepyFace,
    rarity: AchievementRarity.rare,
    condition: SameDayTagCountCondition(ActivityTag.nap, 3),
  ),
  const Achievement(
    id: 'month_streak',
    title: '30日連続暇人',
    description: '30日連続でログを記録する',
    icon: AppIconType.medal,
    rarity: AchievementRarity.rare,
    condition: ConsecutiveDaysCondition(30),
  ),
  const Achievement(
    id: 'all_tags',
    title: '万能暇人',
    description: '全種類のタグを1回以上ログする',
    icon: AppIconType.star,
    rarity: AchievementRarity.rare,
    condition: AllTagsCondition(),
  ),
  const Achievement(
    id: 'tv_6h',
    title: '一気見の鬼',
    description: '動画/TVを6時間以上ログする',
    icon: AppIconType.eye,
    rarity: AchievementRarity.rare,
    condition: SingleSessionDurationCondition(ActivityTag.tv, 360),
  ),
  const Achievement(
    id: 'nap_30',
    title: '昼寝の王',
    description: '昼寝を30回ログする',
    icon: AppIconType.crown,
    rarity: AchievementRarity.rare,
    condition: TagCountCondition(ActivityTag.nap, 30),
  ),
  const Achievement(
    id: 'nothing_3h',
    title: '無の悟り',
    description: '「何もしない」を3時間以上ログする',
    icon: AppIconType.galaxy,
    rarity: AchievementRarity.rare,
    condition: SingleSessionDurationCondition(ActivityTag.nothing, 180),
  ),
  const Achievement(
    id: 'log_100',
    title: '100件達成',
    description: '合計100件のログを記録する',
    icon: AppIconType.hundred,
    rarity: AchievementRarity.rare,
    condition: TotalCountCondition(100),
  ),
  const Achievement(
    id: 'walk_20',
    title: '散歩マスター',
    description: '散歩を20回ログする',
    icon: AppIconType.mountain,
    rarity: AchievementRarity.rare,
    condition: TagCountCondition(ActivityTag.walk, 20),
  ),
  const Achievement(
    id: 'read_30',
    title: '読書家認定',
    description: '読書を30回ログする',
    icon: AppIconType.openBook,
    rarity: AchievementRarity.rare,
    condition: TagCountCondition(ActivityTag.read, 30),
  ),
  const Achievement(
    id: 'game_total_24h',
    title: '廃ゲーマー',
    description: 'ゲームを合計24時間ログする',
    icon: AppIconType.joystick,
    rarity: AchievementRarity.rare,
    condition: TagDurationCondition(ActivityTag.game, 1440),
  ),
  const Achievement(
    id: 'creative_10',
    title: 'クリエイター',
    description: '創作を10回ログする',
    icon: AppIconType.paintbrush,
    rarity: AchievementRarity.rare,
    condition: TagCountCondition(ActivityTag.creative, 10),
  ),
  const Achievement(
    id: 'cafe_15',
    title: 'カフェ大好き人間',
    description: 'カフェを15回ログする',
    icon: AppIconType.coffee,
    rarity: AchievementRarity.rare,
    condition: TagCountCondition(ActivityTag.cafe, 15),
  ),
  const Achievement(
    id: 'nap_3_consecutive',
    title: '連続昼寝週間',
    description: '昼寝を3日連続でログする',
    icon: AppIconType.calendarTear,
    rarity: AchievementRarity.rare,
    condition: AndCondition([
      ConsecutiveDaysCondition(3),
      TagCountCondition(ActivityTag.nap, 3),
    ]),
  ),
  const Achievement(
    id: 'bath_total_10h',
    title: 'お風呂大好き',
    description: 'お風呂を合計10時間ログする',
    icon: AppIconType.shower,
    rarity: AchievementRarity.rare,
    condition: TagDurationCondition(ActivityTag.bath, 600),
  ),
  const Achievement(
    id: 'nothing_total_24h',
    title: '怠惰の達人',
    description: '「何もしない」を合計24時間ログする',
    icon: AppIconType.rock,
    rarity: AchievementRarity.rare,
    condition: TagDurationCondition(ActivityTag.nothing, 1440),
  ),
  const Achievement(
    id: 'log_5_in_day',
    title: '記録魔',
    description: '1日に5件以上ログする',
    icon: AppIconType.pencil,
    rarity: AchievementRarity.rare,
    condition: SameDayTagCountCondition(ActivityTag.other, 5),
  ),
  const Achievement(
    id: 'exercise_20',
    title: '運動習慣',
    description: '運動を20回ログする',
    icon: AppIconType.weightlifting,
    rarity: AchievementRarity.rare,
    condition: TagCountCondition(ActivityTag.exercise, 20),
  ),
  const Achievement(
    id: 'music_20h',
    title: '音楽で生きる',
    description: '音楽を合計20時間ログする',
    icon: AppIconType.musicNotes,
    rarity: AchievementRarity.rare,
    condition: TagDurationCondition(ActivityTag.music, 1200),
  ),
  const Achievement(
    id: 'social_20',
    title: '話し好き',
    description: 'おしゃべりを20回ログする',
    icon: AppIconType.speechBubble,
    rarity: AchievementRarity.rare,
    condition: TagCountCondition(ActivityTag.social, 20),
  ),
  const Achievement(
    id: 'dawn_logger',
    title: '夜明けの暇人',
    description: '夜明け（5〜6時）にログを記録する',
    icon: AppIconType.sunriseMountain,
    rarity: AchievementRarity.rare,
    condition: TimeOfDayCondition(startHour: 5, endHour: 6),
  ),

  // ========== LEGENDARY (👑) ==========

  const Achievement(
    id: 'himajin_king',
    title: '完全なる暇人',
    description: '100日連続でログを記録する',
    icon: AppIconType.trophy,
    rarity: AchievementRarity.legendary,
    condition: ConsecutiveDaysCondition(100),
  ),
  const Achievement(
    id: 'nothing_master',
    title: '無の王',
    description: '「何もしない」を合計100時間ログする',
    icon: AppIconType.blackCircle,
    rarity: AchievementRarity.legendary,
    condition: TagDurationCondition(ActivityTag.nothing, 6000),
  ),
  const Achievement(
    id: 'nap_legend',
    title: '昼寝の神',
    description: '昼寝を100回ログする',
    icon: AppIconType.moon,
    rarity: AchievementRarity.legendary,
    condition: TagCountCondition(ActivityTag.nap, 100),
  ),
  const Achievement(
    id: 'log_500',
    title: '500件の記録',
    description: '合計500件のログを記録する',
    icon: AppIconType.books,
    rarity: AchievementRarity.legendary,
    condition: TotalCountCondition(500),
  ),
  const Achievement(
    id: 'walk_legend',
    title: '歩く暇人',
    description: '散歩を合計100時間ログする',
    icon: AppIconType.globe,
    rarity: AchievementRarity.legendary,
    condition: TagDurationCondition(ActivityTag.walk, 6000),
  ),

  // ========== HIDDEN 隠し実績 ==========

  const Achievement(
    id: 'hidden_3am',
    title: '深夜3時の孤独',
    description: '夜中3時にログを記録した',
    icon: AppIconType.nightCity,
    rarity: AchievementRarity.rare,
    isHidden: true,
    condition: TimeOfDayCondition(startHour: 3, endHour: 4),
  ),
  const Achievement(
    id: 'hidden_nap_in_morning',
    title: '朝から昼寝',
    description: '午前中（6〜12時）に昼寝をログした',
    icon: AppIconType.sunrise,
    rarity: AchievementRarity.uncommon,
    isHidden: true,
    condition: AndCondition([
      FirstTagCondition(ActivityTag.nap),
      TimeOfDayCondition(startHour: 6, endHour: 12),
    ]),
  ),
  const Achievement(
    id: 'hidden_nap_50',
    title: '昼寝50回',
    description: '昼寝を50回ログした',
    icon: AppIconType.dizzyStars,
    rarity: AchievementRarity.legendary,
    isHidden: true,
    condition: TagCountCondition(ActivityTag.nap, 50),
  ),
  const Achievement(
    id: 'hidden_all_in_one_day',
    title: '完璧な暇日',
    description: '1日に昼寝・散歩・動画をすべてログした',
    icon: AppIconType.sparkles,
    rarity: AchievementRarity.rare,
    isHidden: true,
    condition: SameDayCombinationCondition([
      ActivityTag.nap,
      ActivityTag.walk,
      ActivityTag.tv,
    ]),
  ),
  const Achievement(
    id: 'hidden_50_streak',
    title: '暇人半年連続',
    description: '50日連続でログを記録した',
    icon: AppIconType.target,
    rarity: AchievementRarity.legendary,
    isHidden: true,
    condition: ConsecutiveDaysCondition(50),
  ),
];

final int kVisibleAchievementCount =
    kAllAchievements.where((a) => !a.isHidden).length;
